<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ImageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Insert authors images
        DB::table('images')->insert([
            [
                'path' => 'authors/images/user.jpg',
                'imageable_id' => 1,
                'imageable_type' => 'App\Models\Author',
                'is_profile' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'path' => 'authors/1662235215053-Mihailo-Lalic.jpg',
                'imageable_id' => 2,
                'imageable_type' => 'App\Models\Author',
                'is_profile' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'path' => 'authors/1662235215053-Molijer.jpg',
                'imageable_id' => 3,
                'imageable_type' => 'App\Models\Author',
                'is_profile' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'path' => 'authors/1662235215053-Danilo-Kis.jpg',
                'imageable_id' => 4,
                'imageable_type' => 'App\Models\Author',
                'is_profile' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'path' => 'authors/1662235215053-Marko-Miljanov.jpg',
                'imageable_id' => 5,
                'imageable_type' => 'App\Models\Author',
                'is_profile' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'path' => 'authors/1662235215053-Miroslav-Krleza.jpg',
                'imageable_id' => 6,
                'imageable_type' => 'App\Models\Author',
                'is_profile' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'path' => 'authors/1662235215053-Migel-Servantes.jpg',
                'imageable_id' => 7,
                'imageable_type' => 'App\Models\Author',
                'is_profile' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'path' => 'authors/1662235215053-Milos-Crnjanski.jpg',
                'imageable_id' => 8,
                'imageable_type' => 'App\Models\Author',
                'is_profile' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'path' => 'authors/1662235215053-Lav-Tolstoj.jpg',
                'imageable_id' => 9,
                'imageable_type' => 'App\Models\Author',
                'is_profile' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'path' => 'authors/1662235215052-Borisav-Stankovic.jpg',
                'imageable_id' => 10,
                'imageable_type' => 'App\Models\Author',
                'is_profile' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'path' => 'authors/1662235215053-Nikolaj-Gogolj.jpg',
                'imageable_id' => 11,
                'imageable_type' => 'App\Models\Author',
                'is_profile' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'path' => 'authors/1662235215053-Vilijam-Sekspir.jpg',
                'imageable_id' => 12,
                'imageable_type' => 'App\Models\Author',
                'is_profile' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'path' => 'authors/1662235215052-Aleksandar-Sergejevic-Puskin.jpg',
                'imageable_id' => 13,
                'imageable_type' => 'App\Models\Author',
                'is_profile' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'path' => 'authors/1662235215053-Mesa-Selimovic.jpg',
                'imageable_id' => 14,
                'imageable_type' => 'App\Models\Author',
                'is_profile' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'path' => 'authors/1662235215052-Ivo-Andric.jpg',
                'imageable_id' => 15,
                'imageable_type' => 'App\Models\Author',
                'is_profile' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'path' => 'authors/1662235215053-Ernest-Hemingvej.jpg',
                'imageable_id' => 16,
                'imageable_type' => 'App\Models\Author',
                'is_profile' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'path' => 'authors/1662235215053-JK-Rowling.jpg',
                'imageable_id' => 17,
                'imageable_type' => 'App\Models\Author',
                'is_profile' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'path' => 'authors/1662235215053-Njegos-II.jpg',
                'imageable_id' => 18,
                'imageable_type' => 'App\Models\Author',
                'is_profile' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'path' => 'authors/1662235215053-Onore-de-Balzak.jpg',
                'imageable_id' => 19,
                'imageable_type' => 'App\Models\Author',
                'is_profile' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'path' => 'authors/1662235215053-Homer.jpg',
                'imageable_id' => 20,
                'imageable_type' => 'App\Models\Author',
                'is_profile' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'path' => 'authors/1662235215053-Franc-Kafka.jpg',
                'imageable_id' => 21,
                'imageable_type' => 'App\Models\Author',
                'is_profile' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'path' => 'authors/1662235215052-Djovani-Bokaco.jpg',
                'imageable_id' => 22,
                'imageable_type' => 'App\Models\Author',
                'is_profile' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'path' => 'authors/1662235215053-Francesko-Petrarka.jpg',
                'imageable_id' => 23,
                'imageable_type' => 'App\Models\Author',
                'is_profile' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'path' => 'authors/1662235215053-Sofokle.jpg',
                'imageable_id' => 24,
                'imageable_type' => 'App\Models\Author',
                'is_profile' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'path' => 'authors/1662235215052-Alber-Kami.jpg',
                'imageable_id' => 25,
                'imageable_type' => 'App\Models\Author',
                'is_profile' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // Insert books images
        DB::table('images')->insert([
            [
                'path' => 'books/1662236333073-Hari-Poter-i-Kamen-Mudrosti.jpg',
                'imageable_id' => 1,
                'imageable_type' => 'App\Models\Book',
                'is_profile' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'path' => 'books/1662236333073-Hari-Poter-i-Dvorana-Tajni.jpg',
                'imageable_id' => 2,
                'imageable_type' => 'App\Models\Book',
                'is_profile' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'path' => 'books/1662236333073-Hari-Poter-i-zatvorenik-iz-Askabana.jpg',
                'imageable_id' => 3,
                'imageable_type' => 'App\Models\Book',
                'is_profile' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'path' => 'books/1662236333074-Na-Drini-cuprija.jpg',
                'imageable_id' => 4,
                'imageable_type' => 'App\Models\Book',
                'is_profile' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'path' => 'books/1662236333073-Gorski-Vijenac.jpg',
                'imageable_id' => 5,
                'imageable_type' => 'App\Models\Book',
                'is_profile' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'path' => 'books/1662236333073-Lelejska-Gora.jpg',
                'imageable_id' => 6,
                'imageable_type' => 'App\Models\Book',
                'is_profile' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'path' => 'books/1662236333074-Tvrdica.jpg',
                'imageable_id' => 7,
                'imageable_type' => 'App\Models\Book',
                'is_profile' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'path' => 'books/1662236333074-Rani-jadi.jpg',
                'imageable_id' => 8,
                'imageable_type' => 'App\Models\Book',
                'is_profile' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'path' => 'books/1662236333074-Primjeri-cojstva-i-junastva.jpg',
                'imageable_id' => 9,
                'imageable_type' => 'App\Models\Book',
                'is_profile' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'path' => 'books/1662236333073-Gospoda-Glembajevi.jpg',
                'imageable_id' => 10,
                'imageable_type' => 'App\Models\Book',
                'is_profile' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'path' => 'books/1662236333073-Don-Kihot.jpg',
                'imageable_id' => 11,
                'imageable_type' => 'App\Models\Book',
                'is_profile' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'path' => 'books/1662236333074-Seobe.jpg',
                'imageable_id' => 12,
                'imageable_type' => 'App\Models\Book',
                'is_profile' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'path' => 'books/1662236333073-Ana-Karenjina.jpg',
                'imageable_id' => 13,
                'imageable_type' => 'App\Models\Book',
                'is_profile' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'path' => 'books/1662236333074-Necista-krv.jpg',
                'imageable_id' => 14,
                'imageable_type' => 'App\Models\Book',
                'is_profile' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'path' => 'books/1662236333074-Revizor.jpg',
                'imageable_id' => 15,
                'imageable_type' => 'App\Models\Book',
                'is_profile' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'path' => 'books/1662236333074-Romeo-i-Julija.jpg',
                'imageable_id' => 16,
                'imageable_type' => 'App\Models\Book',
                'is_profile' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'path' => 'books/1662236333073-Cigani.jpg',
                'imageable_id' => 17,
                'imageable_type' => 'App\Models\Book',
                'is_profile' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'path' => 'books/1662236333073-Gilgames.jpg',
                'imageable_id' => 18,
                'imageable_type' => 'App\Models\Book',
                'is_profile' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'path' => 'books/1662236333073-Dervis-i-smrt.jpg',
                'imageable_id' => 19,
                'imageable_type' => 'App\Models\Book',
                'is_profile' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'path' => 'books/1662236333074-Stranac-i-more.jpg',
                'imageable_id' => 20,
                'imageable_type' => 'App\Models\Book',
                'is_profile' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'path' => 'books/1662236333074-Cica-Gorio.jpg',
                'imageable_id' => 21,
                'imageable_type' => 'App\Models\Book',
                'is_profile' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'path' => 'books/1662236333073-Ilijada.jpg',
                'imageable_id' => 22,
                'imageable_type' => 'App\Models\Book',
                'is_profile' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'path' => 'books/1662236333073-Hamlet.jpg',
                'imageable_id' => 23,
                'imageable_type' => 'App\Models\Book',
                'is_profile' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'path' => 'books/1662236333074-Proces.jpg',
                'imageable_id' => 24,
                'imageable_type' => 'App\Models\Book',
                'is_profile' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'path' => 'books/1662236333074-Prokleta-avlija.jpg',
                'imageable_id' => 25,
                'imageable_type' => 'App\Models\Book',
                'is_profile' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'path' => 'books/1662236333073-Dekameron.jpg',
                'imageable_id' => 26,
                'imageable_type' => 'App\Models\Book',
                'is_profile' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'path' => 'books/1662236333073-Kanconijer.jpg',
                'imageable_id' => 27,
                'imageable_type' => 'App\Models\Book',
                'is_profile' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'path' => 'books/1662236333073-Antigona.jpg',
                'imageable_id' => 28,
                'imageable_type' => 'App\Models\Book',
                'is_profile' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'path' => 'books/1662236333074-Stranac.jpg',
                'imageable_id' => 29,
                'imageable_type' => 'App\Models\Book',
                'is_profile' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
